### ISSUE TITLE
Reservation Error

### ISSUE THREAD

**Issue by bilgehanertan** [anonrig/muzikus#18]
While adding reservation server responds with a status code 422

**Papertrail log:**
```
`Oct 17 01:02:39 muzikus heroku/router at=info method=POST path="/reservations" host=muzik.us request_id=9caa107b-a118-46f4-95fe-41ad88510324 fwd="159.20.68.22,162.158.159.53" dyno=web.1 connect=0ms service=8ms status=422 bytes=1525 protocol=http

Oct 17 01:02:39 muzikus app/web.1 I, [2021-10-17T11:02:38.779853 #4]  INFO -- : [9caa107b-a118-46f4-95fe-41ad88510324] Started POST "/reservations" for 162.158.159.53 at 2021-10-17 11:02:38 +0300

Oct 17 01:02:39 muzikus app/web.1 I, [2021-10-17T11:02:38.780946 #4]  INFO -- : [9caa107b-a118-46f4-95fe-41ad88510324] Processing by ReservationsController#create as */*

Oct 17 01:02:39 muzikus app/web.1 I, [2021-10-17T11:02:38.781014 #4]  INFO -- : [9caa107b-a118-46f4-95fe-41ad88510324]   Parameters: {"utf8"=>"Ygol70vC0JkFsg01UXlJ1Ravl1rTHTyKjq81Qb4abbs_i-aNhh2DR_tdBM7ykdDy4r8Z-aKVdJOA6l71ehrY_A", "authenticity_token"=>"[FILTERED]", "reservation"=>{"room_id"=>"5", "start_at"=>"2021-10-17T08:02:00.708Z", "end_at"=>"2021-10-17T10:02:00.708Z"}}

Oct 17 01:02:39 muzikus app/web.1 W, [2021-10-17T11:02:38.784687 #4]  WARN -- : [9caa107b-a118-46f4-95fe-41ad88510324] HTTP Origin header (https://muzik.us) didn't match request.base_url (http://muzik.us)

Oct 17 01:02:39 muzikus app/web.1 I, [2021-10-17T11:02:38.785005 #4]  INFO -- : [9caa107b-a118-46f4-95fe-41ad88510324] Completed 422 Unprocessable Entity in 4ms (ActiveRecord: 1.2ms | Allocations: 478)

**Oct 17 01:02:39 muzikus app/web.1 F, [2021-10-17T11:02:38.785723 #4] FATAL -- : [9caa107b-a118-46f4-95fe-41ad88510324]**   

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324]   

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:199:in `block in halting'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:512:in `each'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:512:in `invoke_before'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:115:in `block in run_callbacks'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actiontext (6.1.4.1) lib/action_text/rendering.rb:20:in `with_renderer'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actiontext (6.1.4.1) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `instance_exec'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:137:in `run_callbacks'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `block in instrument'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/notifications.rb:203:in `instrument'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activerecord (6.1.4.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/abstract_controller/base.rb:165:in `process'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionview (6.1.4.1) lib/action_view/rendering.rb:39:in `process'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal.rb:190:in `dispatch'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_controller/metal.rb:254:in `dispatch'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `each'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/routing/route_set.rb:842:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] omniauth (2.0.4) lib/omniauth/builder.rb:45:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/etag.rb:27:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/head.rb:12:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) 
lib/action_dispatch/middleware/callbacks.rb:26:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] railties (6.1.4.1) lib/rails/rack/logger.rb:37:in `call_app'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] railties (6.1.4.1) lib/rails/rack/logger.rb:26:in `block in call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:37:in `tagged'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/tagged_logging.rb:99:in `tagged'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] railties (6.1.4.1) lib/rails/rack/logger.rb:26:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/method_override.rb:24:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/runtime.rb:22:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] activesupport (6.1.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/static.rb:24:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] actionpack (6.1.4.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] railties (6.1.4.1) lib/rails/engine.rb:539:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] puma (5.5.0) lib/puma/configuration.rb:249:in `call'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] puma (5.5.0) lib/puma/request.rb:77:in `block in handle_request'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] puma (5.5.0) lib/puma/thread_pool.rb:340:in `with_force_shutdown'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] puma (5.5.0) lib/puma/request.rb:76:in `handle_request'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] puma (5.5.0) lib/puma/server.rb:447:in `process_client'

Oct 17 01:02:39 muzikus app/web.1 [9caa107b-a118-46f4-95fe-41ad88510324] puma (5.5.0) lib/puma/thread_pool.rb:147:in `block in spawn_thread'`
```

**Comment by bilgehanertan** [comment]
Still the same problem with the same error log; I am getting status code: 422 while adding reservations.

**Comment by anonrig** [comment]
The problem was related to communication between Cloudflare and Heroku SSL. Done.
